import 'package:get/get.dart';
import 'local_string.dart';

class LocalizationString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          LocalString.APP_TITLE: 'GCC Water',
          LocalString.LANGUAGE: 'English',
          LocalString.LANGUAGE_SELECTION: 'Language',
          LocalString.PRIVACY_POLICY: 'Privacy Policy',
          LocalString.HOME_PAGE: 'Home',
          LocalString.USER_PROFILE_PAGE: 'User',
          LocalString.userId: 'User ID',
          LocalString.waterConnection: 'Water Connection',
          LocalString.APP_VERSION: '1.0.2',
          LocalString.CHECK_UPDATE: 'Check Update',
          LocalString.aboutUsDetails:
              'GCC Billing System is a digital platform designed to simplify water bill management for both Gazipur residents and service providers from Gazipur City Corporation. Key features include application for water connection, tube well installation application, monthly bill, complaint related to certain issues, billing information, old billing information and many more facilities.',
          LocalString.inImplementation: 'In planning and implementation',
          LocalString.PROJECT_TITLE: 'GCC Water\nGazipur City Corporation.',
          LocalString.GOVT_INFO: 'Gazipur City Corporation',
          LocalString.TECHNICAL_INFO: 'Technical Support',
          LocalString.TECHNICAL_INFO_ADDRESS:
              'Addie Soft Limited\nUnit A,Level 12, 27 Shaptak Square \nRoad 27(New 16),Dhanmondi DHAKA 1205 Bangladesh.',
          LocalString.contactUs:
              "If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us at:\nADDIE Soft Limited\nUnit A,Level 12, 27 Shaptak Square,\nRoad 27(New 16),Dhanmondi, Dhaka-1209, Bangladesh.",
          LocalString.changeToTHisPrivacyPolicy:
              'We may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page.\n\nThis policy is effective as of 2023-10-01',
          LocalString.childrenPrivacy:
              'We do not intended for, nor do we knowingly collect information from children under 18 years old.',
          LocalString.dataSafetyDetails:
              'While using any of Our Services, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: \n\nEmail address\nDisplay name\nPhone number\nNID/ Birth Certificate\nHolding, Road, Zone, Ward, Address.',
          LocalString.policy:
              'ADDIE Soft Ltd built the GCC Water app as a Free app. This SERVICE is provided by Gazipur City Corporation(GCC) at no cost and is intended for use as is.\n\nThis page is used to inform visitors regarding our policies with the collection, use, and disclosure of Personal Information if anyone decided to use our Service.\n\nIf you choose to use our Service, then you agree to the collection and use of information in relation to this policy. The information that we collect is used for providing and improving the Service. We will not use or share your information with anyone except as described in this Privacy Policy.',
          LocalString.dataSafety: "Data Safety",
          LocalString.childrensPrivacy: 'Children\'s Privacy',
          LocalString.changesPrivacyPolicy: 'Changes to this Privacy Policy',
          LocalString.contactWithUs: 'Contact Us',
          LocalString.usageData: 'Usage Data',
          LocalString.usageDataDetails:
              'We store all of your personal information on our common server system for verification and ensure that your information is secured with us. We do not share your personal data with third-party advertisers or ad networks.',
          LocalString.Deep_Tube_Well: "Deep Tube Well",
          LocalString.Monthly_Water_bill: "Monthly Water Bills",
          LocalString.My_Complain: 'My Complains',
          LocalString.Old_application_Request: 'Old Application',
          LocalString.About: 'About',
          LocalString.PRIVACY_POLICY: 'Privacy Policy',
          LocalString.Gcc: 'Gazipur City Corporation',
          LocalString.Project_Title: 'Water Supply Billing Management System',
          LocalString.Enter_valid_info: 'Enter valid info',
          LocalString.Select_valid_info: 'Select valid info',
          LocalString.Select_option: 'Select an Option',
          LocalString.Select_Client_type: 'Select Client Type first',
          LocalString.Done_btn: 'Done',
          LocalString.Attached_file: 'Attach File',
          LocalString.Upload: 'Upload',
          LocalString.Water_Line: 'Water Line',
          LocalString.title: 'Water Supply Billing Management System',
          LocalString.loginString: 'Login',
          LocalString.logoutString: 'Logout',
          LocalString.password: 'Password',
          LocalString.Forget_password: 'Forget Password',
          LocalString.Dont_have_an_account: 'Don\'t have an account ?',
          LocalString.Create_Account: 'Create Account',
          LocalString.Enter_min_digit: 'Enter minimum 6 digit',
          LocalString.Check_account: 'Check Account',
          LocalString.We_ve_sent_an_otp: 'We\'ve sent an otp code to the',
          LocalString.Please_check_your_sms: 'Please check your sms',
          LocalString.Verify: 'Verify',
          LocalString.NewPass: 'New Password',
          LocalString.Set_New_Password: 'Set a new password',
          LocalString.Password_Change: 'Change Password',
          LocalString.notMatchPassword: 'Password not match',
          LocalString.Old_Password: 'Old Password',
          LocalString.No_empty: '',
          LocalString.Oops_something_went_wrong: 'Oops! something went wrong',
          LocalString.WaterApplication: 'Application for Water',
          LocalString.TubewellApplication: 'Aplication for Tubewell',


  LocalString.total_Complain_Received : 'Total\nComplain\nReceived',
  LocalString.complain_Resolved : 'Complain\nResolved',
  LocalString.complain_Pending : 'Complain\nPending',
  LocalString.new_Connection_Request : 'New\nConnection\nRequest',
  LocalString.connection_approved : 'Connection\napproved',
  LocalString.application_Pending : 'Application\nPending',
  LocalString.water_Bill_Management : 'Water Bill Management',
  LocalString.bill_Generated_Month : 'Bill\nGenerated\nThis Month',
  LocalString.bill_Received : 'Bill\nReceived',
  LocalString.due_Bill_Amount : 'Due Bill\nAmount',
  LocalString.tender_Management : 'Tender Management',
  LocalString.ongoing_Tender : 'Ongoing\nTender',
  LocalString.tender_application : 'Tender\napplication',
  LocalString.tender_close : 'Tender\nclose',
  LocalString.complain_management : 'Complain management',
  LocalString.water_connection : 'Water connection',
  LocalString.deep_Tube_well_connection : 'Deep Tube-well connection',
  LocalString.bulb_replacement : 'Bulb Replacement',
  LocalString.e_file_management : 'E-file management',
  LocalString.tender_Approval : 'Tender Approval',
  LocalString.Gcc:'Gazipur City Corporation',
  LocalString.Project_Title:'Water Supply Billing Management System',
  LocalString.no_more_data:'No more data found',
  LocalString.serial_no:'Serial no',
  LocalString.id:'Id',
  LocalString.complain_Id:'Complain Id',
  LocalString.complain_Details:'Complain Details',
  LocalString.status_monitoring:'Status monitoring',
  LocalString.from_User:'From User',
  LocalString.to_User:'To User',
  LocalString.comment:'Comment',
  LocalString.reject:'Reject',
  LocalString.forward:'Forward',
  LocalString.solve:'Solve',
  LocalString.receiver:'Receiver',
  LocalString.select_an_item:'Select  an item',
  LocalString.select_an_option:'Select an option',
  LocalString.type_your_comment:'Type your comment',
  LocalString.deepTubeWellConnection:'Deep TubeWell Connection',
  LocalString.customer_name:'Customer name',
  LocalString.area:'Area',
  LocalString.ward_No:'Ward No',
  LocalString.customerInfo:'Customer Info',
  LocalString.accountNo:'Account No',
  LocalString.customerId:'Customer Id',
  LocalString.holdingNo:'Holding No',
  LocalString.roadNo:'Road No',
  LocalString.address:'Address',
  LocalString.mobile:'Mobile',
  LocalString.customerType:'Customer type',
  LocalString.diatype:'Dia type',
  LocalString.amount:'Amount',
  LocalString.documentAttachment:'Document Attachment',
  LocalString.applicationId:'Application Id',

  LocalString.jobAssign:'Job Assign',
  LocalString.receivingDack:'receiving Dack',
  LocalString.receivingENothi:'Receiving E-Nothi',
  LocalString.office:'Office',
  LocalString.selectOfficeType:'Select Office Type',
  LocalString.department:'Department',
  LocalString.section:'Section',
  LocalString.designation:'Designation',
  LocalString.jobConfiguration:'Job Configuration',
  LocalString.confirm:'Confirm',
  LocalString.thisWillDeletePermanently:'This will delete this permanently. You can not undo this action.',
  LocalString.no:'No',
  LocalString.yes:'Yes',
  LocalString.delete:'Delete',
  LocalString.jobHistory:'Job History',
  LocalString.job:'Job',
  LocalString.date:'Date',
  LocalString.close:'Close',
  LocalString.referenceNo:'Reference No',
  LocalString.source:'Source',
  LocalString.subject:'Subject',
  LocalString.description:'Description',
  LocalString.decision:'Decision',
  LocalString.sender:'Sender',
  LocalString.cancel:'Cancel',
  LocalString.confirmation:'Confirmation',
  LocalString.doYouWantToConfirm:'Do you want to confirm ?',
  LocalString.reference:'Reference',

  LocalString.tenderApprovalDetails:'Tender Approval Details',
  LocalString.tenderTitle:'Tender Title',
  LocalString.publishDate:'Publish Date',
  LocalString.participantName:'Participant Name',
  LocalString.authorityName:'Authority Name',
  LocalString.email:'Email',
  LocalString.submittedDate:'Submitted Date',
  LocalString.obtainMark:'Obtain Mark',
  LocalString.eligibility:'Eligibility',
  LocalString.criteria:'Criteria',
  LocalString.documentTitle:'Document Title',
  LocalString.hasDocument:'Has Document',
  LocalString.view:'View',
  LocalString.additionalDocument:'Additional Document',
  LocalString.nextAuthorityInfo:'Next Authority Info',
  LocalString.approvalAuthority:'Approval Authority',
  LocalString.selectZone:'Select Zone',
  LocalString.notifyUser:'Notify User',
  LocalString.needToBack:'Need to back',
  LocalString.youDoNotHaveThisPermission:'You do not have this permission',
  LocalString.needToReject:'Need to Reject',
  LocalString.back:'Back',
  LocalString.transactionAlreadyCompleted:'Transaction Already Completed',
  LocalString.doYouWantToReject:'Do you want to Reject?',
  LocalString.doYouWantToBack:'Do you want to Back?',
  LocalString.submit:'Submit',
  LocalString.doYouWantToForward:'Do you want to Forward?',
  LocalString.loadList:'Load List',
  LocalString.approvalTransactionType:'Approval Transaction Type',
  LocalString.tansactionDetails:'Transaction Details',

  LocalString.applicationReceived:'Application received',
  LocalString.oldApplicationRequest:'Old application request',
  LocalString.applicantInformation:'Applicant information',
  LocalString.applicantName:'ApplicantName',
  LocalString.nidOrBirthCertificateNo:'NID or Birth Certificate No',
  LocalString.customerAddress:'Customer address',
  LocalString.applicationDetails:'Application details',
  LocalString.applicationDate:'Application Date',
  LocalString.typOfApplication:'Type of application',
  LocalString.fatherHusbandInstitution:'Father/Husband/Institution',
  LocalString.streetAreaMahallaMouza:'Street/Area/Mahalla/Mouza',
  LocalString.clientType:'Client Type',
  LocalString.monthlyBillAmount:'Monthly bill amount',
  LocalString.status:'Status',
  LocalString.name:'Name',
  LocalString.ok:'Ok',
  LocalString.zone:'Zone',
  LocalString.selectDepartmentType:'Select Department Type',
  LocalString.selectSectionType:'Select Section Type',
  LocalString.noDataAvailable:'No Data Available',
  LocalString.pullType:'Pull Type',
  LocalString.pullNo:'Pull No',
  LocalString.region:'Region',
  LocalString.ward:'Ward',
  LocalString.apply:'Apply',
  LocalString.bulbReplacementApplication:'Bulb Replacement Application',
  LocalString.typeOfBulb:'Type of bulb',
  LocalString.selectBulbType:'Select Bulb Type',
  LocalString.watt:'Watt',
  LocalString.typeWard:'Type ward',
  LocalString.brand:'Brand',
  LocalString.replacementDate:'Replacement Date',
  LocalString.reasonForReplacement:'Reason for replacement',
  LocalString.active:'Active',
  LocalString.reset:'Reset',
  LocalString.update:'Update',
  LocalString.save:'Save',
  LocalString.bulbReplacementDetails:'Bulb Replacement Details',


        },
        'bn_BD': {
          LocalString.zone: 'জোন',
          LocalString.selectDepartmentType: 'ডিপার্টমেন্ট টাইপ নির্বাচন করুন',
          LocalString.selectSectionType: 'সিলেক্ট সেকশন টাইপ',
          LocalString.noDataAvailable: 'কোন ডেটা উপলব্ধ নেই',
          LocalString.pullType:'পুল টাইপ',
          LocalString.pullNo:'পুল নাম্বার',
          LocalString.region:'অঞ্চল',
          LocalString.ward: 'ওয়ার্ড',
          LocalString.apply:'প্রয়োগ করুন',
          LocalString.bulbReplacementApplication:'বাল্ব প্রতিস্থাপন অ্যাপ্লিকেশন',
          LocalString.typeOfBulb: 'বাল্বের প্রকার',
          LocalString.selectBulbType: 'বাল্ব টাইপ নির্বাচন করুন',
          LocalString.watt:'ওয়াট',
          LocalString.typeWard:'টাইপ ওয়ার্ড',
          LocalString.brand:'Brand',
          LocalString.replacementDate:'প্রতিস্থাপনের তারিখ',
          LocalString.reasonForReplacement: 'প্রতিস্থাপনের কারণ',
          LocalString.active:'সক্রিয়',
          LocalString.reset: 'রিসেট',
          LocalString.update:'আপডেট',
          LocalString.save: 'সংরক্ষণ করুন',
          LocalString.bulbReplacementDetails: 'বাল্ব প্রতিস্থাপনের বিবরণ',
          LocalString.ok: 'ঠিক আছে',
          LocalString.applicationReceived:'আবেদন গৃহীত হয়েছে',
          LocalString.oldApplicationRequest:'পুরাতন আবেদনের অনুরোধ',
          LocalString.applicantInformation:'আবেদনকারীর তথ্য',
          LocalString.applicantName:'আবেদনকারীর নাম',
          LocalString.nidOrBirthCertificateNo:'এনআইডি বা জন্ম সনদ নম্বর',
          LocalString.customerAddress:'গ্রাহকের ঠিকানা',
          LocalString.applicationDetails:'আবেদনের বিবরণ',
          LocalString.applicationDate:'আবেদনের তারিখ',
          LocalString.typOfApplication: 'আবেদনের ধরন',
          LocalString.fatherHusbandInstitution:'পিতা/স্বামী/প্রতিষ্ঠান',
          LocalString.streetAreaMahallaMouza:'রাস্তা/এরিয়া/মহল্লা/মৌজা',
          LocalString.clientType:'ক্লায়েন্ট টাইপ',
          LocalString.monthlyBillAmount:'মাসিক বিলের পরিমাণ',
          LocalString.status: 'স্থিতি',
          LocalString.name:'নাম',
          LocalString.tenderApprovalDetails: 'টেন্ডার অনুমোদনের বিবরণ',
          LocalString.tenderTitle: 'টেন্ডার শিরোনাম',
          LocalString.publishDate:'প্রকাশের তারিখ',
          LocalString.participantName:'অংশগ্রহণকারীর নাম',
          LocalString.authorityName:'কর্তৃপক্ষের নাম',
          LocalString.email: 'ইমেল',
          LocalString.submittedDate: 'জমা দেওয়ার তারিখ',
          LocalString.obtainMark: 'মার্ক প্রাপ্ত করুন',
          LocalString.eligibility: 'যোগ্যতা',
          LocalString.criteria: 'মাপদণ্ড',
          LocalString.documentTitle: 'ডকুমেন্ট টাইটেল',
          LocalString.hasDocument:'দস্তাবেজ আছে',
          LocalString.view: 'দেখুন',
          LocalString.additionalDocument:'অতিরিক্ত নথি',
          LocalString.nextAuthorityInfo: 'পরবর্তী কর্তৃপক্ষের তথ্য',
          LocalString.approvalAuthority:'অনুমোদন কর্তৃপক্ষ',
          LocalString.selectZone: 'জোন নির্বাচন করুন',
          LocalString.notifyUser: 'ব্যবহারকারীকে অবহিত করুন',
          LocalString.needToBack: 'ব্যাক করতে হবে',
          LocalString.youDoNotHaveThisPermission:'আপনার কাছে এই অনুমতি নেই',
          LocalString.needToReject: 'প্রত্যাখ্যান করতে হবে',
          LocalString.back: 'ব্যাক',
          LocalString.transactionAlreadyCompleted:'লেনদেন ইতিমধ্যেই সম্পন্ন হয়েছে',
          LocalString.doYouWantToReject:'আপনি কি প্রত্যাখ্যান করতে চান?',
          LocalString.doYouWantToBack:'আপনি কি ফিরে যেতে চান?',
          LocalString.submit: 'জমা দিন',
          LocalString.doYouWantToForward:'আপনি কি ফরোয়ার্ড করতে চান?',
          LocalString.loadList: 'লোড তালিকা',
          LocalString.approvalTransactionType:'অনুমোদন লেনদেনের ধরন',
          LocalString.tansactionDetails:'লেনদেনের বিবরণ',
          LocalString.jobAssign:'জব অ্যাসাইন',
          LocalString.receivingDack: 'ডাক গ্রহণ',
          LocalString.receivingENothi: 'ই-নোথি গ্রহণ করা',
          LocalString.office:'অফিস',
          LocalString.selectOfficeType: 'অফিস টাইপ নির্বাচন করুন',
          LocalString.department:'বিভাগ',
          LocalString.section: 'বিভাগ',
          LocalString.designation:'পদবী',
          LocalString.jobConfiguration:'জব কনফিগারেশন',
          LocalString.confirm:'নিশ্চিত করুন',
          LocalString.thisWillDeletePermanently:'এটি স্থায়ীভাবে মুছে দেবে। আপনি এই ক্রিয়াটিকে পূর্বাবস্থায় ফিরিয়ে আনতে পারবেন না৷',
          LocalString.no: 'না',
          LocalString.yes:'হ্যাঁ',
          LocalString.delete:'মুছে ফেলা',
          LocalString.jobHistory: 'চাকরির ইতিহাস',
          LocalString.job:'জব',
          LocalString.date:'তারিখ',
          LocalString.close:'ক্লোজ',
          LocalString.referenceNo:'রেফারেন্স নং',
          LocalString.source: 'উৎস',
          LocalString.subject: 'বিষয়',
          LocalString.description: 'বিবরণ',
          LocalString.decision:'সিদ্ধান্ত',
          LocalString.sender: 'প্রেরক',
          LocalString.cancel:'বাতিল',
          LocalString.confirmation:'নিশ্চিতকরণ',
          LocalString.doYouWantToConfirm:'আপনি কি নিশ্চিত করতে চান?',
          LocalString.reference: 'রেফারেন্স',
          LocalString.deepTubeWellConnection: 'ডিপ টিউবওয়েল সংযোগ',
          LocalString.customer_name:'গ্রাহকের নাম',
          LocalString.area:'এরিয়া',
          LocalString.ward_No:'ওয়ার্ড নং',
          LocalString.customerInfo:'গ্রাহকের তথ্য',
          LocalString.accountNo:'অ্যাকাউন্ট নং',
          LocalString.customerId:'গ্রাহক আইডি',
          LocalString.holdingNo:'হোল্ডিং না',
          LocalString.roadNo:'রাস্তা নং',
          LocalString.address:'ঠিকানা',
          LocalString.mobile:'মুঠোফোন',
          LocalString.customerType:'ব্যবহারকারীর ধরন',
          LocalString.diatype:'ডিয়া টাইপ',
          LocalString.amount:'অ্যামাউন্ট',
          LocalString.documentAttachment:'ডকুমেন্ট সংযুক্তি',
          LocalString.applicationId:'অ্যাপ্লিকেশন আইডি',
          LocalString.complain_Id: 'অভিযোগ আইডি',
          LocalString.complain_Details: 'অভিযোগের বিবরণ',
          LocalString.status_monitoring: 'স্থিতি পর্যবেক্ষণ',
          LocalString.from_User: 'ব্যবহারকারীর কাছ থেকে',
          LocalString.to_User: 'ব্যবহারকারীর কাছে',
          LocalString.comment: 'মন্তব্য',
          LocalString.reject: 'প্রত্যাখ্যান করুন',
          LocalString.forward:'ফরওয়ার্ড',
          LocalString.solve: 'সমাধান',
          LocalString.receiver:'রিসিভার',
          LocalString.select_an_item: 'একটি আইটেম নির্বাচন করুন',
          LocalString.select_an_option: 'একটি বিকল্প নির্বাচন করুন',
          LocalString.type_your_comment:'আপনার মন্তব্য টাইপ করুন',
          LocalString.id:'আইডি',
          LocalString.no_more_data: 'আর কোন তথ্য পাওয়া যায়নি',
          LocalString.serial_no:'ক্রমিক নম্বর',
          LocalString.Gcc: 'গাজীপুর সিটি কর্পোরেশন',
          LocalString.Project_Title:'ওয়াটার সাপ্লাই বিলিং ম্যানেজমেন্ট সিস্টেম',
          LocalString.complain_management : 'অভিযোগ ব্যবস্থাপনা',
          LocalString.water_connection : 'জল সংযোগ',
          LocalString.deep_Tube_well_connection : 'ডিপ টিউব-ওয়েল সংযোগ',
          LocalString.bulb_replacement : 'বাল্ব প্রতিস্থাপন',
          LocalString.e_file_management : 'ই-ফাইল ব্যবস্থাপনা',
          LocalString.tender_Approval : 'টেন্ডার অনুমোদন',
          LocalString.total_Complain_Received : 'মোট\nঅভিযোগ\nপ্রাপ্ত',
          LocalString.complain_Resolved : 'অভিযোগ\nসমাধান হয়েছে',
          LocalString.complain_Pending : 'অভিযোগ\nমুলতুবি',
          LocalString.new_Connection_Request : 'নতুন\nসংযোগ\nঅনুরোধ',
          LocalString.connection_approved : 'সংযোগ\অনুমোদিত',
          LocalString.application_Pending : 'অ্যাপ্লিকেশন\nপেন্ডিং',
          LocalString.water_Bill_Management : 'ওয়াটার বিল ম্যানেজমেন্ট',
          LocalString.bill_Generated_Month : 'বিল\nজেনারেট হয়েছে\nএই মাসে',
          LocalString.bill_Received : 'বিল\nপ্রাপ্ত',
          LocalString.due_Bill_Amount : 'বকেয়া বিল\nঅ্যামাউন্ট',
          LocalString.tender_Management : 'টেন্ডার ম্যানেজমেন্ট',
          LocalString.ongoing_Tender : 'চলমান\nদরপত্র',
          LocalString.tender_application : 'টেন্ডার\nআবেদন',
          LocalString.tender_close : 'টেন্ডার\nক্লোজ',
          LocalString.logoutString:'লগ আউট',
          LocalString.TubewellApplication: 'টিউবওয়েলের জন্য আবেদন',
          LocalString.WaterApplication: 'পানির জন্য আবেদন',
          LocalString.APP_TITLE: 'GCC Water',
          LocalString.LANGUAGE: 'বাংলা',
          LocalString.LANGUAGE_SELECTION: 'ভাষা',
          LocalString.PRIVACY_POLICY: 'গোপনীয়তা নীতি',
          LocalString.HOME_PAGE: 'হোম',
          LocalString.USER_PROFILE_PAGE: 'ব্যবহারকারী',
          LocalString.userId: 'ব্যবহারকারীর আইডি',
          LocalString.waterConnection: 'পানি সংযোগ',
          LocalString.Deep_Tube_Well: "গভীর নলকূপ",
          LocalString.Monthly_Water_bill: "মাসিক পানির বিল",
          LocalString.My_Complain: 'আমার অভিযোগ',
          LocalString.Old_application_Request: 'পুরানো আবেদনের অনুরোধ',
          LocalString.About: 'সম্পর্কিত',
          LocalString.PRIVACY_POLICY: 'গোপনীয়িত নীতি',
          LocalString.Gcc: 'গাজীপুর সিটি কর্পোরেশন',
          LocalString.Project_Title: 'পানি সরবরাহ বিলিং ম্যানেজমেন্ট সিস্টেম',
          LocalString.APP_VERSION: '১.০.২',
          LocalString.CHECK_UPDATE: 'চেক আপডেট',
          LocalString.aboutUsDetails:
              'জিসিসি বিলিং সিস্টেম হল একটি ডিজিটাল প্ল্যাটফর্ম যা গাজীপুর বাসীদের এবং গাজীপুর সিটি কর্পোরেশন থেকে সেবা প্রদানকারী উভয়ের জন্য পানির বিল ব্যবস্থাপনাকে সহজ করার জন্য ডিজাইন করা হয়েছে। মূল বৈশিষ্ট্যগুলির মধ্যে রয়েছে পানির সংযোগের জন্য আবেদন, টিউবওয়েল স্থাপন এর আবেদন, মাসিক বিল, কতিপয় বিষয় সম্পর্কিত অভিযোগ, বিলিং তথ্য, পুরাতন বিলিং তথ্য এবং আর ও অনেক সুবিধা। ',
          LocalString.inImplementation: 'পরিকল্পনা ও বাস্তবায়নে',
          LocalString.PROJECT_TITLE:
              'জিসিসি বিলিং সিস্টেম\nগাজীপুর সিটি কর্পোরেশন।',
          LocalString.GOVT_INFO: 'গাজীপুর সিটি কর্পোরেশন',
          LocalString.TECHNICAL_INFO: 'প্রযুক্তিগত সহায়তা',
          LocalString.TECHNICAL_INFO_ADDRESS:
              'অ্যাডি সফট লিমিটেড\nইউনিট এ,লেভেল 12, 27 শাপ্তক স্কোয়ার \nরোড 27(নতুন 16), ধানমন্ডি ঢাকা 1205 বাংলাদেশ।',
          LocalString.contactUs:
              "আমাদের গোপনীয়তা নীতি সম্পর্কে আপনার কোনো প্রশ্ন বা পরামর্শ থাকলে, আমাদের সাথে যোগাযোগ করতে দ্বিধা করবেন না:\nADDIE Soft Limited\nUnit A, Level 12, 27 Shaptak Square,\nরাস্তা ২৭(নতুন ১৬), ধানমন্ডি, ঢাকা-১২০৭, বাংলাদেশ।",
          LocalString.changeToTHisPrivacyPolicy:
              'আমরা মাঝে মাঝে আমাদের গোপনীয়তা নীতি আপডেট করতে পারি। সুতরাং, যেকোনো পরিবর্তনের জন্য আপনাকে পর্যায়ক্রমে এই পৃষ্ঠাটি পর্যালোচনা করার পরামর্শ দেওয়া হচ্ছে। আমরা এই পৃষ্ঠায় নতুন গোপনীয়তা নীতি পোস্ট করার মাধ্যমে যেকোনো পরিবর্তন সম্পর্কে আপনাকে অবহিত করব।\n\nএই নীতিটি 2023-10-01 থেকে কার্যকর হবে',
          LocalString.childrenPrivacy:
              'আমরা জেনেশুনে ১৮ বছরের কম বয়সী শিশুদের কাছ থেকে তথ্য সংগ্রহ করি না।',
          LocalString.dataSafetyDetails:
              'আমাদের যেকোনো পরিষেবা ব্যবহার করার সময়, আমরা আপনাকে কিছু ব্যক্তিগতভাবে শনাক্তযোগ্য তথ্য প্রদান করতে বলতে পারি যা আপনার সাথে যোগাযোগ বা শনাক্ত করতে ব্যবহার করা যেতে পারে। ব্যক্তিগতভাবে শনাক্তকরণযোগ্য তথ্য অন্তর্ভুক্ত হতে পারে, কিন্তু এতে সীমাবদ্ধ নয়: \n\nইমেল\nনাম\nফোন নম্বর\nNID/ জন্মের সনদপত্র নম্বর\nহোল্ডিং, রাস্তা, অঞ্চল, ওয়ার্ড, ঠিকানা।',
          LocalString.policy:
              'ADDIE Soft Ltd একটি বিনামূল্যের অ্যাপ হিসেবে জিসিসি বিলিং সিস্টেম অ্যাপ তৈরি করেছে। এই পরিষেবাটি গাজীপুর সিটি কর্পোরেশন (জিসিসি) দ্বারা বিনা খরচে প্রদান করা হয় এটি ব্যবহার করার উদ্দেশ্যে।\n\nএই পৃষ্ঠাটি ব্যক্তিগত তথ্য সংগ্রহ, ব্যবহার এবং প্রকাশের সাথে আমাদের নীতি সম্পর্কে দর্শকদের জানানোর জন্য ব্যবহার করা হয়েছে যদি কেউ সিদ্ধান্ত নেয় আমাদের পরিষেবা ব্যবহার করতে।\n\nআপনি যদি আমাদের পরিষেবা ব্যবহার করতে চান, তাহলে আপনি এই নীতির সাথে সম্পর্কিত তথ্য সংগ্রহ এবং ব্যবহারে সম্মত হন৷ আমরা যে তথ্য সংগ্রহ করি তা পরিষেবা প্রদান এবং উন্নতির জন্য ব্যবহার করা হয়। এই গোপনীয়তা নীতিতে বর্ণিত ব্যতীত আমরা আপনার তথ্য কারো সাথে ব্যবহার বা শেয়ার করব না।',
          LocalString.dataSafety: "ডেটা সেফটি",
          LocalString.childrensPrivacy: 'শিশুদের গোপনীয়তা',
          LocalString.changesPrivacyPolicy: 'এই গোপনীয়তা নীতিতে পরিবর্তন',
          LocalString.contactWithUs: 'আমাদের সাথে যোগাযোগ করুন',
          LocalString.usageData: 'ব্যবহৃত তথ্য',
          LocalString.usageDataDetails:
              'আমরা যাচাইয়ের জন্য আপনার সমস্ত ব্যক্তিগত তথ্য আমাদের সাধারণ সার্ভার সিস্টেমে সংরক্ষণ করি এবং নিশ্চিত করি যে আপনার তথ্য আমাদের কাছে সুরক্ষিত আছে। আমরা তৃতীয় পক্ষের বিজ্ঞাপনদাতা বা বিজ্ঞাপন নেটওয়ার্কের সাথে আপনার ব্যক্তিগত ডেটা শেয়ার করি না।',
          LocalString.Enter_valid_info: 'সঠিক তথ্য প্রদান করুন',
          LocalString.Select_valid_info: 'সঠিক তথ্য নির্বাচন করুন',
          LocalString.Select_option: 'যেকোনো একটি নির্বাচন করুন',
          LocalString.Select_Client_type: 'প্রথমে গ্রাহকের ধরণ',
          LocalString.Done_btn: 'সম্পন্ন',
          LocalString.Attached_file: 'নথি সংযুক্ত করুন',
          LocalString.Upload: 'আপলোড করুন',
          LocalString.Water_Line: 'পানির সংযোগ',
          LocalString.title: 'ওয়াটার সাপ্লাই বিলিং ম্যানেজমেন্ট সিস্টেম',
          LocalString.loginString: 'লগআউট',
          LocalString.password: 'পাসওয়ার্ড',
          LocalString.Forget_password: 'পাসওয়ার্ড ভুলে গেছেন',
          LocalString.Dont_have_an_account: 'অ্যাকাউন্ট নেই?',
          LocalString.Create_Account: 'অ্যাকাউন্ট তৈরি করুন',
          LocalString.Enter_min_digit: 'সর্বনিম্ন 6 সংখ্যা লিখুন',
          LocalString.Check_account: 'অ্যাকাউন্ট চেক করুন',
          LocalString.We_ve_sent_an_otp: 'আমরা একটি otp কোড পাঠিয়েছি ',
          LocalString.No_empty: ' নাম্বারে',
          LocalString.Please_check_your_sms:
              'অনুগ্রহ করে আপনার এসএমএস চেক করুন।',
          LocalString.Verify: 'যাচাই করুন',
          LocalString.NewPass: 'নতুন পাসওয়ার্ড',
          LocalString.Set_New_Password: 'নতুন পাসওয়ার্ড সেট করুন',
          LocalString.Password_Change: 'পাসওয়ার্ড পরিবর্তন করুন',
          LocalString.notMatchPassword: 'পাসওয়ার্ড মিলছে না',
          LocalString.Old_Password: 'বর্তমান পাসওয়ার্ড',
          LocalString.Oops_something_went_wrong: 'ওহো! কিছু ভুল হয়ে।',
        }
      };
}
