import 'package:get/get.dart';
import 'local_string.dart';

class LocalizationString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          LocalString.APP_TITLE: 'GCC Water',
          LocalString.LANGUAGE: 'English',
          LocalString.LANGUAGE_SELECTION: 'Language',
          LocalString.PRIVACY_POLICY: 'Privacy Policy',
          LocalString.HOME_PAGE: 'Home',
          LocalString.USER_PROFILE_PAGE: 'User',
          LocalString.userId: 'User ID',
          LocalString.APP_VERSION: '1.0.2',
          LocalString.CHECK_UPDATE: 'Check Update',
          LocalString.About: 'About',
          LocalString.PRIVACY_POLICY: 'Privacy Policy',
          LocalString.Enter_valid_info: 'Enter valid info',
          LocalString.Select_valid_info: 'Select valid info',
          LocalString.Done_btn: 'Done',
          LocalString.Upload: 'Upload',
          LocalString.title: 'Water Supply Billing Management System',
          LocalString.loginString: 'Login',
          LocalString.logoutString: 'Logout',
          LocalString.password: 'Password',
          LocalString.Forget_password: 'Forget Password',
          LocalString.Dont_have_an_account: 'Don\'t have an account ?',
          LocalString.Create_Account: 'Create Account',
          LocalString.Enter_min_digit: 'Enter minimum 6 digit',
          LocalString.Check_account: 'Check Account',
          LocalString.We_ve_sent_an_otp: 'We\'ve sent an otp code to the',
          LocalString.Please_check_your_sms: 'Please check your sms',
          LocalString.Verify: 'Verify',
          LocalString.NewPass: 'New Password',
          LocalString.Set_New_Password: 'Set a new password',
          LocalString.Password_Change: 'Change Password',
          LocalString.notMatchPassword: 'Password not match',
          LocalString.Old_Password: 'Old Password',
          LocalString.No_empty: '',
          LocalString.Oops_something_went_wrong: 'Oops! something went wrong',

LocalString.no_more_data:'No more data found',
LocalString.serial_no:'Serial no',
LocalString.id:'Id',
LocalString.from_User:'From User',
LocalString.to_User:'To User',
LocalString.comment:'Comment',
LocalString.reject:'Reject',
LocalString.forward:'Forward',
LocalString.solve:'Solve',
LocalString.receiver:'Receiver',
LocalString.select_an_item:'Select  an item',
LocalString.type_your_comment:'Type your comment',
LocalString.area:'Area',
LocalString.ward_No:'Ward No',
LocalString.holdingNo:'Holding No',
LocalString.roadNo:'Road No',
LocalString.address:'Address',
LocalString.mobile:'Mobile',
LocalString.office:'Office',
LocalString.selectOfficeType:'Select Office Type',
LocalString.department:'Department',
LocalString.section:'Section',
LocalString.designation:'Designation',
LocalString.confirm:'Confirm',
LocalString.no:'No',
LocalString.yes:'Yes',
LocalString.delete:'Delete',
LocalString.job:'Job',
LocalString.date:'Date',
LocalString.close:'Close',
LocalString.description:'Description',
LocalString.cancel:'Cancel',
LocalString.confirmation:'Confirmation',
LocalString.doYouWantToConfirm:'Do you want to confirm ?',
LocalString.email:'Email',
LocalString.view:'View',
LocalString.nextAuthorityInfo:'Next Authority Info',
LocalString.selectZone:'Select Zone',
LocalString.notifyUser:'Notify User',
LocalString.back:'Back',
LocalString.doYouWantToReject:'Do you want to Reject?',
LocalString.doYouWantToBack:'Do you want to Back?',
LocalString.submit:'Submit',
LocalString.doYouWantToForward:'Do you want to Forward?',
LocalString.loadList:'Load List',
LocalString.status:'Status',
LocalString.name:'Name',
LocalString.ok:'Ok',
LocalString.zone:'Zone',
LocalString.region:'Region',
LocalString.ward:'Ward',
LocalString.apply:'Apply',
LocalString.active:'Active',
LocalString.reset:'Reset',
LocalString.update:'Update',
LocalString.save:'Save',



        },
        'bn_BD': {
          LocalString.zone: 'জোন',

          LocalString.noDataAvailable: 'কোন ডেটা উপলব্ধ নেই',

          LocalString.region:'অঞ্চল',
          LocalString.ward: 'ওয়ার্ড',
          LocalString.apply:'প্রয়োগ করুন',
          LocalString.active:'সক্রিয়',
          LocalString.reset: 'রিসেট',
          LocalString.update:'আপডেট',
          LocalString.save: 'সংরক্ষণ করুন',
          LocalString.ok: 'ঠিক আছে',
          LocalString.status: 'স্থিতি',
          LocalString.name:'নাম',
          LocalString.email: 'ইমেল',
          LocalString.view: 'দেখুন',
          LocalString.nextAuthorityInfo: 'পরবর্তী কর্তৃপক্ষের তথ্য',
          LocalString.selectZone: 'জোন নির্বাচন করুন',
          LocalString.notifyUser: 'ব্যবহারকারীকে অবহিত করুন',
          LocalString.back: 'ব্যাক',
          LocalString.doYouWantToReject:'আপনি কি প্রত্যাখ্যান করতে চান?',
          LocalString.doYouWantToBack:'আপনি কি ফিরে যেতে চান?',
          LocalString.submit: 'জমা দিন',
          LocalString.doYouWantToForward:'আপনি কি ফরোয়ার্ড করতে চান?',
          LocalString.loadList: 'লোড তালিকা',
          LocalString.office:'অফিস',
          LocalString.selectOfficeType: 'অফিস টাইপ নির্বাচন করুন',
          LocalString.department:'বিভাগ',
          LocalString.section: 'বিভাগ',
          LocalString.designation:'পদবী',
          LocalString.confirm:'নিশ্চিত করুন',
          LocalString.no: 'না',
          LocalString.yes:'হ্যাঁ',
          LocalString.delete:'মুছে ফেলা',
          LocalString.job:'জব',
          LocalString.date:'তারিখ',
          LocalString.close:'ক্লোজ',
          LocalString.description: 'বিবরণ',
          LocalString.cancel:'বাতিল',
          LocalString.confirmation:'নিশ্চিতকরণ',
          LocalString.doYouWantToConfirm:'আপনি কি নিশ্চিত করতে চান?',
          LocalString.area:'এরিয়া',
          LocalString.ward_No:'ওয়ার্ড নং',
          LocalString.holdingNo:'হোল্ডিং না',
          LocalString.roadNo:'রাস্তা নং',
          LocalString.address:'ঠিকানা',
          LocalString.mobile:'মুঠোফোন',
          LocalString.from_User: 'ব্যবহারকারীর কাছ থেকে',
          LocalString.to_User: 'ব্যবহারকারীর কাছে',
          LocalString.comment: 'মন্তব্য',
          LocalString.reject: 'প্রত্যাখ্যান করুন',
          LocalString.forward:'ফরওয়ার্ড',
          LocalString.solve: 'সমাধান',
          LocalString.receiver:'রিসিভার',
          LocalString.select_an_item: 'একটি আইটেম নির্বাচন করুন',
          LocalString.type_your_comment:'আপনার মন্তব্য টাইপ করুন',
          LocalString.id:'আইডি',
          LocalString.no_more_data: 'আর কোন তথ্য পাওয়া যায়নি',
          LocalString.serial_no:'ক্রমিক নম্বর',
          LocalString.logoutString:'লগ আউট',
          LocalString.APP_TITLE: 'GCC Water',
          LocalString.LANGUAGE: 'বাংলা',
          LocalString.LANGUAGE_SELECTION: 'ভাষা',
          LocalString.PRIVACY_POLICY: 'গোপনীয়তা নীতি',
          LocalString.HOME_PAGE: 'হোম',
          LocalString.USER_PROFILE_PAGE: 'ব্যবহারকারী',
          LocalString.userId: 'ব্যবহারকারীর আইডি',
          LocalString.About: 'সম্পর্কিত',
          LocalString.PRIVACY_POLICY: 'গোপনীয়িত নীতি',
          LocalString.APP_VERSION: '১.০.২',
          LocalString.CHECK_UPDATE: 'চেক আপডেট',
          LocalString.Enter_valid_info: 'সঠিক তথ্য প্রদান করুন',
          LocalString.Select_valid_info: 'সঠিক তথ্য নির্বাচন করুন',
          LocalString.Done_btn: 'সম্পন্ন',
          LocalString.Upload: 'আপলোড করুন',
          LocalString.title: 'ওয়াটার সাপ্লাই বিলিং ম্যানেজমেন্ট সিস্টেম',
          LocalString.loginString: 'লগআউট',
          LocalString.password: 'পাসওয়ার্ড',
          LocalString.Forget_password: 'পাসওয়ার্ড ভুলে গেছেন',
          LocalString.Dont_have_an_account: 'অ্যাকাউন্ট নেই?',
          LocalString.Create_Account: 'অ্যাকাউন্ট তৈরি করুন',
          LocalString.Enter_min_digit: 'সর্বনিম্ন 6 সংখ্যা লিখুন',
          LocalString.Check_account: 'অ্যাকাউন্ট চেক করুন',
          LocalString.We_ve_sent_an_otp: 'আমরা একটি otp কোড পাঠিয়েছি ',
          LocalString.No_empty: ' নাম্বারে',
          LocalString.Please_check_your_sms:
              'অনুগ্রহ করে আপনার এসএমএস চেক করুন।',
          LocalString.Verify: 'যাচাই করুন',
          LocalString.NewPass: 'নতুন পাসওয়ার্ড',
          LocalString.Set_New_Password: 'নতুন পাসওয়ার্ড সেট করুন',
          LocalString.Password_Change: 'পাসওয়ার্ড পরিবর্তন করুন',
          LocalString.notMatchPassword: 'পাসওয়ার্ড মিলছে না',
          LocalString.Old_Password: 'বর্তমান পাসওয়ার্ড',
          LocalString.Oops_something_went_wrong: 'ওহো! কিছু ভুল হয়ে।',
        }
      };
}
